In [4]:
import pandas as pd
import numpy as np



In [19]:
df = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv")

In [20]:
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [21]:
df.count()

Customer ID    1000
Gender         1000
Age            1000
Salary         1000
Product ID     1000
Price          1000
Purchased      1000
dtype: int64

In [26]:
gender = pd.get_dummies(df['Gender'],drop_first=True)

In [27]:
gender

Male
0       0
1       1
2       0
3       0
4       0
..    ...
995     1
996     1
997     0
998     1
999     0

[1000 rows x 1 columns]

In [25]:
df.head()

# one hot coding

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [28]:
df = pd.concat([df,gender],axis=1)

In [29]:
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased  Male
0            1  Female   49   61000        P01   2000          1     0
1            2    Male   36   30000        P02   2000          1     1
2            3  Female   26   81000        P02   3500          1     0
3            4  Female   32   74000        P01   7000          0     0
4            5  Female   42   56000        P01   5000          0     0

In [31]:
x = df[['Male','Age','Salary','Price']].to_numpy()

In [32]:
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [33]:
y = df['Purchased'].to_numpy()

In [34]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [39]:
x_train

array([[ 1.08347268, -1.09076887, -1.30749141,  0.30934614],
       [ 1.08347268,  0.97668947, -1.60377078,  1.39955279],
       [-0.92295821,  0.0906359 , -1.56144515,  0.30934614],
       ...,
       [-0.92295821,  1.34587846,  1.35902286, -1.32596384],
       [-0.92295821, -0.72157988,  0.97809225, -1.32596384],
       [-0.92295821, -1.53379565, -1.05353767,  0.30934614]])

In [40]:
x_test

array([[ 0.91370804,  0.84165121, -0.92674628,  0.29135523],
       [-1.0944415 ,  0.84165121,  0.09493083,  1.3460348 ],
       [ 0.91370804, -1.16805526, -0.79903664, -1.29066412],
       [-1.0944415 , -0.19785214, -0.84160652,  1.3460348 ],
       [ 0.91370804, -0.96015459, -0.8841764 ,  0.29135523],
       [ 0.91370804,  0.70305076, -0.671327  , -1.29066412],
       [-1.0944415 ,  0.07934876, -1.39501496,  1.3460348 ],
       [-1.0944415 , -0.12855191, -1.5227246 ,  0.29135523],
       [-1.0944415 , -1.65315683, -1.48015472, -0.49965444],
       [ 0.91370804,  1.396053  , -0.75646676,  0.29135523],
       [ 0.91370804,  0.77235099,  0.35035011,  0.29135523],
       [-1.0944415 ,  0.56445032, -0.84160652,  1.3460348 ],
       [-1.0944415 ,  0.49515009,  0.05236095,  1.3460348 ],
       [-1.0944415 ,  0.98025166,  1.67001638, -1.29066412],
       [ 0.91370804, -0.05925169, -0.58618724, -0.49965444],
       [ 0.91370804, -0.33645258,  0.69090915, -1.29066412],
       [-1.0944415 ,  0.

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
k= 5
knn = KNeighborsClassifier(n_neighbors=k)

In [43]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [44]:
y_pred = knn.predict(x_test)

In [45]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [46]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.765

In [51]:
import pickle

In [52]:
with open('knn_model.pickle','wb') as f:
  pickle.dump(knn,f)

In [53]:
with open('scaler.pickle','wb') as f:
  pickle.dump(scaler,f)


In [54]:

!ls

knn_model.pickle  sample_data  scaler.pickle
